on: push
name: Android Emulator runner
jobs:
  connected-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Init gradle wrapper
        run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle wrapper
        run: ./gradlew build  
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck

