name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prototype_rust_wrapper
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo check
